pipeline {
    agent any
    environment {
        SERVER_PORT = '8081'
    }
    stages {
        stage('Build Docker image') {
            steps {
                sh 'docker build -t femelloffm/go-calculator:1.0 ./docker'
            }
        }
        stage('Remove old container') {
            when {
                not {
                    expression {
                        return sh(returnStdout: true, script: 'docker ps -a -f name=go-calculator -q').trim() == ""
                    }
                }
            }
            steps {
                sh 'docker stop go-calculator'
                sh 'docker rm go-calculator'
            }
        }
        stage('Run Docker container') {
            steps {
                sh 'docker run --name go-calculator -p ${SERVER_PORT}:8080 -d femelloffm/go-calculator:1.0'
            }
        }
        stage('Stress testing') {
            steps {
                dir('gatling') {
                    sh './gradlew gatlingRun -Dport=${SERVER_PORT}'
                }
            }
            post {
                always {
                    gatlingArchive()
                }
            }
        }
    }
}
